all:
  hosts:
    R1:
      ansible_host: 192.168.255.1
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: cisco.ios.ios
      ansible_user: admin
      ansible_password: admin
      ansible_become_password: admin
