- name: ホスト名を変更する
  hosts: all
  gather_facts: no
  connection: ansible.netcommon.network_cli
  become: yes
  become_method: enable

  tasks:
    - name: ホスト名を更新
      cisco.ios.ios_config:
        backup: yes
        lines:
          - hostname Router1
